In [1]:
import numpy as np  

In [10]:
myArr = np.array([[3,5,7,43,6]], np.int8)

In [12]:
myArr

array([[ 3,  5,  7, 43,  6]], dtype=int8)

In [14]:
myArr[0,1]

5

In [5]:
myArr.shape

(1, 5)

In [6]:
myArr.dtype

dtype('int8')

In [8]:
myArr[0,1] = 45

In [11]:
myArr[0]

array([ 3,  5,  7, 43,  6], dtype=int8)

In [15]:
myArr

array([[ 3,  5,  7, 43,  6]], dtype=int8)

# Array Creation: Conversion from other python structures

In [16]:
listArr = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [17]:
listArr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [19]:
listArr.dtype

dtype('int32')

In [20]:
listArr.shape

(3, 3)

In [21]:
listArr.size

9

In [22]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [29]:
zeros = np.zeros((2,5))

In [30]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.shape

(2, 5)

In [36]:
rng = np.arange(15)

In [37]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
lspace = np.linspace(1,4,5)

In [48]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [50]:
emp = np.empty((4,6))

In [51]:
emp

array([[8.73807605e-312, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 1.42419937e-306, 5.30276956e+180],
       [6.00736842e-067, 5.38183340e+097, 3.70306639e-033,
        3.42042811e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        4.98318128e-037, 3.27043808e+179, 6.25286746e-091],
       [6.22667173e-038, 2.59027906e-144, 1.16442250e-028,
        9.44872517e-143, 7.23188049e-308, 2.08600674e-308]])

In [52]:
emp_like = np.empty_like(lspace)

In [53]:
emp_like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [54]:
ide = np.identity(45)

In [55]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [56]:
ide.shape

(45, 45)

In [57]:
arr = np.arange(99)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [61]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [63]:
arr = arr.reshape(3,33)

In [64]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [67]:
arr = arr.ravel()

In [68]:
arr.shape

(99,)

In [69]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [74]:
ar = np.array(x)

In [71]:
ar.sum(axis=0)

array([12,  8,  9])

In [72]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [77]:
ar.flat

In [79]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


# array dimensions

In [80]:
ar.ndim

2

In [81]:
ar.size

9

In [82]:
ar.nbytes

36

In [83]:
one = np.array([1,3,4,545,2])

# give the index of maximum element

In [84]:
one.argmax()

3

In [86]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [87]:
for item in one.argsort():
    print(one[item])

1
2
3
4
545


In [90]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [91]:
ar.argmin()

8

In [92]:
ar.argmax()

6

In [93]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [94]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [96]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [95]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [98]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [100]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [101]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [102]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [105]:
ar2 = np.array([
    [1, 2, 1],
    [4, 0, 6],
    [8, 1, 0]
])

In [107]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [108]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [110]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [114]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [115]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [116]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [117]:
ar.sum()

29

In [118]:
ar.max()

7

In [119]:
ar.min()

0

In [120]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [122]:
g5 = np.where(ar>5)

In [125]:
type(g5)

tuple

In [126]:
np.count_nonzero(ar)

8

In [127]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [128]:
import sys

In [131]:
py_ar = [0, 4, 55, 2]

In [132]:
np_ar = np.array(py_ar)

In [137]:
sys.getsizeof(1)*len(py_ar)

112

In [138]:
np_ar.itemsize * np_ar.size

16

In [140]:
np_ar.tolist()

[0, 4, 55, 2]